services:
  - type: web
    name: disaster-tweet-classifier
    env: python
    buildCommand: pip install -r requirements.txt && pip install --upgrade pip setuptools wheel
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
